spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ManyToMany?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: vdb-manager
    password: sanria@#77
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
springdoc:
  swagger-ui:
    path: /swaggerui

NotificationServiceURL: http://localhost:9090/api/v1/notification